2022-01-21T18:08:06.573714+0000 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (18683), thread 'MainThread' (139914581428032):
Traceback (most recent call last):

> File "/usr/share/nginx/html/teste/template_python_files/header/header.py", line 34, in <module>
    header(title, author)
    │      │      └ ''
    │      └ ''
    └ <function header at 0x7f40659ca200>

  File "/home/mic/.local/lib/python3.10/site-packages/snoop/tracer.py", line 170, in simple_wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ ('', '')
           └ <function header at 0x7f4066b4bd90>

  File "/usr/share/nginx/html/teste/template_python_files/header/header.py", line 28, in header
    template = env.get_template("header.php")
               │   └ <function Environment.get_template at 0x7f4065c39c60>
               └ <jinja2.environment.Environment object at 0x7f40657eb910>

  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
           │    │              │     └ None
           │    │              └ 'header.php'
           │    └ <function Environment._load_template at 0x7f4065c39bd0>
           └ <jinja2.environment.Environment object at 0x7f40657eb910>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               │    │      │    │     │     │    │            └ None
               │    │      │    │     │     │    └ <function Environment.make_globals at 0x7f4065c39ea0>
               │    │      │    │     │     └ <jinja2.environment.Environment object at 0x7f40657eb910>
               │    │      │    │     └ 'header.php'
               │    │      │    └ <jinja2.environment.Environment object at 0x7f40657eb910>
               │    │      └ <function BaseLoader.load at 0x7f4065c3b760>
               │    └ <jinja2.loaders.FileSystemLoader object at 0x7f40657e8190>
               └ <jinja2.environment.Environment object at 0x7f40657eb910>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 │    │          │            └ 'header.php'
                                 │    │          └ <jinja2.environment.Environment object at 0x7f40657eb910>
                                 │    └ <function FileSystemLoader.get_source at 0x7f4065c3b880>
                                 └ <jinja2.loaders.FileSystemLoader object at 0x7f40657e8190>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
          │                └ 'header.php'
          └ <class 'jinja2.exceptions.TemplateNotFound'>

jinja2.exceptions.TemplateNotFound: header.php
2022-01-21T18:36:22.092916+0000 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (19603), thread 'MainThread' (140623026583360):
Traceback (most recent call last):

> File "/usr/share/nginx/html/poems_folding_menu/hp_menu/rand.py", line 44, in <module>
    rand()
    └ <function rand at 0x7fe5583b2290>

  File "/home/mic/.local/lib/python3.10/site-packages/snoop/tracer.py", line 170, in simple_wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ ()
           └ <function rand at 0x7fe5592e1c60>

  File "/usr/share/nginx/html/poems_folding_menu/hp_menu/rand.py", line 38, in rand
    template = env.get_template("hp_menu.tpl")
               │   └ <function Environment.get_template at 0x7fe558629d80>
               └ <jinja2.environment.Environment object at 0x7fe5583be830>

  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
           │    │              │     └ None
           │    │              └ 'hp_menu.tpl'
           │    └ <function Environment._load_template at 0x7fe558629cf0>
           └ <jinja2.environment.Environment object at 0x7fe5583be830>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               │    │      │    │     │     │    │            └ None
               │    │      │    │     │     │    └ <function Environment.make_globals at 0x7fe558629fc0>
               │    │      │    │     │     └ <jinja2.environment.Environment object at 0x7fe5583be830>
               │    │      │    │     └ 'hp_menu.tpl'
               │    │      │    └ <jinja2.environment.Environment object at 0x7fe5583be830>
               │    │      └ <function BaseLoader.load at 0x7fe55862b880>
               │    └ <jinja2.loaders.FileSystemLoader object at 0x7fe5583bfa60>
               └ <jinja2.environment.Environment object at 0x7fe5583be830>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 │    │          │            └ 'hp_menu.tpl'
                                 │    │          └ <jinja2.environment.Environment object at 0x7fe5583be830>
                                 │    └ <function FileSystemLoader.get_source at 0x7fe55862b9a0>
                                 └ <jinja2.loaders.FileSystemLoader object at 0x7fe5583bfa60>
  File "/home/mic/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
          │                └ 'hp_menu.tpl'
          └ <class 'jinja2.exceptions.TemplateNotFound'>

jinja2.exceptions.TemplateNotFound: hp_menu.tpl
